services:
  django_app:
    image: ${NAME:-django-deploy}:${TAG:-latest}
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
    volumes:
      - /var/www/${NAME:-django-deploy}/static/:${STATICFILES_PATH:-/app/static/}
      - /var/www/${NAME:-django-deploy}/media/:${MEDIA_PATH:-/app/media/}
    ports:
      - 8000:8000
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: