services:
  django:
    profiles: 
      - django
    image: ${NAME:-django-deploy}:${TAG:-latest}
    build:
      context: ${BACKEND_SRC:-..}
      dockerfile: ${BACKEND_SRC:-..}/Dockerfile
    volumes:
      - /var/www/${NAME:-django-deploy}/static/:${STATICFILES_PATH:-/app/static/}
      - /var/www/${NAME:-django-deploy}/media/:${MEDIA_PATH:-/app/media/}
    ports:
      - 8000:8000
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db:/var/lib/postgresql/data
  dotnet_frontend:
    profiles: 
      - dotnet_frontend
    image: ${NAME:-dotnet-deploy}:${TAG:-latest}
    build:
      context: ${FRONTEND_SRC:-..}
      dockerfile: ${FRONTEND_SRC:-..}Dockerfile
    depends_on:
      - ${BACKEND_PROFILE:-django}
volumes:
  db: