services:
  django_app:
    image: ${NAME:-django-deploy}:${TAG:-latest}
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
    ports:
      - 8000:8000
    depends:
      - postgres_db
  postgres_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}